### ISSUE TITLE
Add support for more types of notification

### ISSUE THREAD

**Issue by timsayshey** [bravocognos/git-submodule-concurrent#1]

**Comment by thalesfsp** [comment]
Hi, @timsayshey! I assume that you are requesting other types of notifications, for example, OS notification. Is that right? Because `gsc` already prints` Done` in` stdout` when all threads finish.

**Comment by timsayshey** [comment]
Was on the old version when I made this ticket but now that you mention it an OS notification would be pretty slick when the task completes. For mac you can run the following command to output a notification: `tput bel` then for Ubuntu you can run `notify-send "Hydra task completed"`

**Comment by thalesfsp** [comment]
> Was on the old version when I made this ticket but now that you mention it an OS notification would be pretty slick when the task completes. For mac you can run the following command to output a notification: `tput bel` then for Ubuntu you can run `notify-send "Hydra task completed"`

Nice! I will close this issue and add it as an idea 💡!
